-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 09:02:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crowsoftdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crowsoftdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crowsoftdb` DEFAULT CHARACTER SET utf8 ;
USE `crowsoftdb` ;

-- -----------------------------------------------------
-- Table `crowsoftdb`.`UserAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowsoftdb`.`UserAccount` (
  `idUserAccount` INT NOT NULL AUTO_INCREMENT,
  `EmailAddress` VARCHAR(150) NOT NULL COMMENT 'User email address used as username as well. ',
  `Password` VARCHAR(50) NOT NULL,
  `FirstName` VARCHAR(60) NOT NULL,
  `LastName` VARCHAR(60) NOT NULL,
  `TelephoneNo` VARCHAR(45) NOT NULL,
  `AddressLine` VARCHAR(150) NULL,
  `County` VARCHAR(45) NULL,
  `Country` VARCHAR(60) NULL,
  `EirCode` VARCHAR(20) NULL,
  `CompanyName` VARCHAR(45) NULL,
  `TypeUser` VARCHAR(15) NOT NULL,
  `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUserAccount`),
  UNIQUE INDEX `idUserAccount_UNIQUE` (`idUserAccount` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`DefaultFeature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowsoftdb`.`DefaultFeature` (
  `idDefaultFeature` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(100) NOT NULL,
  `Measurement` VARCHAR(20) NOT NULL,
  `UnitPrice` DECIMAL(8,2) NOT NULL,
  `DefaultFeature` TINYINT NULL,
  PRIMARY KEY (`idDefaultFeature`),
  UNIQUE INDEX `idBuildingCost_UNIQUE` (`idDefaultFeature` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`BuildingQuote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowsoftdb`.`BuildingQuote` (
  `idBuildingQuote` INT NOT NULL AUTO_INCREMENT,
  `UserAccount_idUserAccount` INT NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `MeasurementType` VARCHAR(25) NOT NULL,
  `Height` INT NOT NULL,
  `Width` INT NOT NULL,
  `Depth` INT NOT NULL,
  `PurposeOfBuilding` VARCHAR(150) NULL,
  `BuildingSize` INT NULL,
  `TotalCost` DECIMAL(12,2) NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Status` VARCHAR(10) NULL,
  `TimeFrame` INT NULL,
  `DateUpdated` DATETIME NULL,
  `UpdatedById` INT NULL,
  PRIMARY KEY (`idBuildingQuote`),
  UNIQUE INDEX `idBuildingQuote_UNIQUE` (`idBuildingQuote` ASC),
  INDEX `fk_BuildingQuote_UserAccount_idx` (`UserAccount_idUserAccount` ASC),
  CONSTRAINT `fk_BuildingQuote_UserAccount`
    FOREIGN KEY (`UserAccount_idUserAccount`)
    REFERENCES `crowsoftdb`.`UserAccount` (`idUserAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`BuildingFeatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowsoftdb`.`BuildingFeatures` (
  `idBuildingFeatures` INT NOT NULL AUTO_INCREMENT,
  `FeatureDescription` VARCHAR(100) NOT NULL,
  `Comments` VARCHAR(150) NULL,
  `Quantity` DECIMAL(10,4) NOT NULL,
  `UnitPrice` DECIMAL(10,2) NOT NULL,
  `TotalCost` DECIMAL(12,2) NULL,
  `BuildingQuote_idBuildingQuote` INT NOT NULL,
  `DefaultFeature_idDefaultFeature` INT NOT NULL,
  PRIMARY KEY (`idBuildingFeatures`, `BuildingQuote_idBuildingQuote`, `DefaultFeature_idDefaultFeature`),
  UNIQUE INDEX `idBuildingFeatures_UNIQUE` (`idBuildingFeatures` ASC),
  INDEX `fk_BuildingFeatures_BuildingQuote1_idx` (`BuildingQuote_idBuildingQuote` ASC),
  INDEX `fk_BuildingFeatures_DefaultFeature1_idx` (`DefaultFeature_idDefaultFeature` ASC),
  CONSTRAINT `fk_BuildingFeatures_BuildingQuote1`
    FOREIGN KEY (`BuildingQuote_idBuildingQuote`)
    REFERENCES `crowsoftdb`.`BuildingQuote` (`idBuildingQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BuildingFeatures_DefaultFeature1`
    FOREIGN KEY (`DefaultFeature_idDefaultFeature`)
    REFERENCES `crowsoftdb`.`DefaultFeature` (`idDefaultFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`BuildingImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crowsoftdb`.`BuildingImage` (
  `idBuildingImage` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(150) NULL,
  `ImagePath` VARCHAR(200) NULL,
  `BuildingQuote_idBuildingQuote` INT NOT NULL,
  PRIMARY KEY (`idBuildingImage`, `BuildingQuote_idBuildingQuote`),
  UNIQUE INDEX `idBuildingImage_UNIQUE` (`idBuildingImage` ASC),
  INDEX `fk_BuildingImage_BuildingQuote1_idx` (`BuildingQuote_idBuildingQuote` ASC),
  CONSTRAINT `fk_BuildingImage_BuildingQuote1`
    FOREIGN KEY (`BuildingQuote_idBuildingQuote`)
    REFERENCES `crowsoftdb`.`BuildingQuote` (`idBuildingQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
