-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 09:10:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crowsoftdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crowsoftdb` ;

-- -----------------------------------------------------
-- Schema crowsoftdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crowsoftdb` DEFAULT CHARACTER SET latin1 ;
USE `crowsoftdb` ;

-- -----------------------------------------------------
-- Table `crowsoftdb`.`AspNetRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`AspNetRoles` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`AspNetRoles` (
  `Id` VARCHAR(128) NOT NULL,
  `Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`AspNetUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`AspNetUsers` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`AspNetUsers` (
  `Id` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(256) NULL DEFAULT NULL,
  `EmailConfirmed` TINYINT(1) NOT NULL,
  `PasswordHash` LONGTEXT NULL DEFAULT NULL,
  `SecurityStamp` LONGTEXT NULL DEFAULT NULL,
  `PhoneNumber` LONGTEXT NULL DEFAULT NULL,
  `PhoneNumberConfirmed` TINYINT(1) NOT NULL,
  `TwoFactorEnabled` TINYINT(1) NOT NULL,
  `LockoutEnd` DATETIME NULL DEFAULT NULL,
  `LockoutEnabled` TINYINT(1) NOT NULL,
  `AccessFailedCount` INT(11) NOT NULL,
  `UserName` VARCHAR(256) NOT NULL,
  `ConcurrencyStamp` LONGTEXT NULL DEFAULT NULL,
  `NormalizedEmail` VARCHAR(256) NULL DEFAULT NULL,
  `NormalizedUserName` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`AspNetUserClaims`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`AspNetUserClaims` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`AspNetUserClaims` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserId` VARCHAR(128) NOT NULL,
  `ClaimType` LONGTEXT NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id` (`Id` ASC),
  INDEX `UserId` (`UserId` ASC),
  CONSTRAINT `ApplicationUser_Claims`
    FOREIGN KEY (`UserId`)
    REFERENCES `crowsoftdb`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`AspNetUserLogins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`AspNetUserLogins` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`AspNetUserLogins` (
  `LoginProvider` VARCHAR(128) NOT NULL,
  `ProviderKey` VARCHAR(128) NOT NULL,
  `UserId` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`, `UserId`),
  INDEX `ApplicationUser_Logins` (`UserId` ASC),
  CONSTRAINT `ApplicationUser_Logins`
    FOREIGN KEY (`UserId`)
    REFERENCES `crowsoftdb`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`AspNetUserRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`AspNetUserRoles` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`AspNetUserRoles` (
  `UserId` VARCHAR(128) NOT NULL,
  `RoleId` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `IdentityRole_Users` (`RoleId` ASC),
  CONSTRAINT `ApplicationUser_Roles`
    FOREIGN KEY (`UserId`)
    REFERENCES `crowsoftdb`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `IdentityRole_Users`
    FOREIGN KEY (`RoleId`)
    REFERENCES `crowsoftdb`.`AspNetRoles` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`UserAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`UserAccount` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`UserAccount` (
  `idUserAccount` INT(11) NOT NULL AUTO_INCREMENT,
  `EmailAddress` VARCHAR(150) NOT NULL COMMENT 'User email address used as username as well. ',
  `FirstName` VARCHAR(60) NOT NULL,
  `LastName` VARCHAR(60) NOT NULL,
  `TelephoneNo` VARCHAR(45) NOT NULL,
  `AddressLine` VARCHAR(150) NULL DEFAULT NULL,
  `County` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(60) NULL DEFAULT NULL,
  `EirCode` VARCHAR(20) NULL DEFAULT NULL,
  `CompanyName` VARCHAR(45) NULL DEFAULT NULL,
  `TypeUser` VARCHAR(15) NOT NULL,
  `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `AspNetUserID` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`idUserAccount`),
  UNIQUE INDEX `idUserAccount_UNIQUE` (`idUserAccount` ASC),
  INDEX `fk_UserAccount_AspNetUsers1_idx` (`AspNetUserID` ASC),
  CONSTRAINT `fk_UserAccount_AspNetUsers1`
    FOREIGN KEY (`AspNetUserID`)
    REFERENCES `crowsoftdb`.`AspNetUsers` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`BuildingQuote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`BuildingQuote` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`BuildingQuote` (
  `idBuildingQuote` INT(11) NOT NULL AUTO_INCREMENT,
  `UserAccount_idUserAccount` INT(11) NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `MeasurementType` VARCHAR(25) NOT NULL,
  `Height` INT(11) NOT NULL,
  `Width` INT(11) NOT NULL,
  `Depth` INT(11) NOT NULL,
  `PurposeOfBuilding` VARCHAR(150) NULL DEFAULT NULL,
  `BuildingSize` INT(11) NULL DEFAULT NULL,
  `TotalCost` DECIMAL(12,2) NULL DEFAULT NULL,
  `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Status` VARCHAR(10) NULL DEFAULT NULL,
  `TimeFrame` INT(11) NULL DEFAULT NULL,
  `DateUpdated` DATETIME NULL DEFAULT NULL,
  `UpdatedById` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idBuildingQuote`),
  UNIQUE INDEX `idBuildingQuote_UNIQUE` (`idBuildingQuote` ASC),
  INDEX `fk_BuildingQuote_UserAccount_idx` (`UserAccount_idUserAccount` ASC),
  CONSTRAINT `fk_BuildingQuote_UserAccount`
    FOREIGN KEY (`UserAccount_idUserAccount`)
    REFERENCES `crowsoftdb`.`UserAccount` (`idUserAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`DefaultFeature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`DefaultFeature` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`DefaultFeature` (
  `idDefaultFeature` INT(11) NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(100) NOT NULL,
  `Measurement` VARCHAR(20) NOT NULL,
  `UnitPrice` DECIMAL(8,2) NOT NULL,
  `DefaultFeature` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idDefaultFeature`),
  UNIQUE INDEX `idBuildingCost_UNIQUE` (`idDefaultFeature` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`BuildingFeatures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`BuildingFeatures` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`BuildingFeatures` (
  `idBuildingFeatures` INT(11) NOT NULL AUTO_INCREMENT,
  `FeatureDescription` VARCHAR(100) NOT NULL,
  `Comments` VARCHAR(150) NULL DEFAULT NULL,
  `Quantity` DECIMAL(10,4) NOT NULL,
  `UnitPrice` DECIMAL(10,2) NOT NULL,
  `TotalCost` DECIMAL(12,2) NULL DEFAULT NULL,
  `BuildingQuote_idBuildingQuote` INT(11) NOT NULL,
  `DefaultFeature_idDefaultFeature` INT(11) NOT NULL,
  PRIMARY KEY (`idBuildingFeatures`, `BuildingQuote_idBuildingQuote`, `DefaultFeature_idDefaultFeature`),
  UNIQUE INDEX `idBuildingFeatures_UNIQUE` (`idBuildingFeatures` ASC),
  INDEX `fk_BuildingFeatures_BuildingQuote1_idx` (`BuildingQuote_idBuildingQuote` ASC),
  INDEX `fk_BuildingFeatures_DefaultFeature1_idx` (`DefaultFeature_idDefaultFeature` ASC),
  CONSTRAINT `fk_BuildingFeatures_BuildingQuote1`
    FOREIGN KEY (`BuildingQuote_idBuildingQuote`)
    REFERENCES `crowsoftdb`.`BuildingQuote` (`idBuildingQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BuildingFeatures_DefaultFeature1`
    FOREIGN KEY (`DefaultFeature_idDefaultFeature`)
    REFERENCES `crowsoftdb`.`DefaultFeature` (`idDefaultFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`BuildingImage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`BuildingImage` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`BuildingImage` (
  `idBuildingImage` INT(11) NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(150) NULL DEFAULT NULL,
  `ImagePath` VARCHAR(200) NULL DEFAULT NULL,
  `BuildingQuote_idBuildingQuote` INT(11) NOT NULL,
  PRIMARY KEY (`idBuildingImage`, `BuildingQuote_idBuildingQuote`),
  UNIQUE INDEX `idBuildingImage_UNIQUE` (`idBuildingImage` ASC),
  INDEX `fk_BuildingImage_BuildingQuote1_idx` (`BuildingQuote_idBuildingQuote` ASC),
  CONSTRAINT `fk_BuildingImage_BuildingQuote1`
    FOREIGN KEY (`BuildingQuote_idBuildingQuote`)
    REFERENCES `crowsoftdb`.`BuildingQuote` (`idBuildingQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`Dummy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`Dummy` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`Dummy` (
  `PersonID` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `LastName` VARCHAR(255) NULL DEFAULT NULL,
  `FirstName` VARCHAR(255) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `City` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `crowsoftdb`.`__EFMigrationsHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crowsoftdb`.`__EFMigrationsHistory` ;

CREATE TABLE IF NOT EXISTS `crowsoftdb`.`__EFMigrationsHistory` (
  `MigrationId` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `ProductVersion` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
