pipeline {
  agent any
  stages {
    stage('Checkout code') {
	  	steps {
				checkout scm				
			  }
			}
	stage ('Build MVC'){
		steps {
			cd /Projects/crowsoftmvc
			dotnet build
			}
		}

	}
}




