pipeline {
	agent any
	stages {
		stage('Checkout Code'){
			step {
		  	checkout scm				
			}	
		}
		stage ('Build MVC'){
			step {
			sh 'cd /Projects/crowsoftmvc'
			sh 'dotnet build'
			}
		}

		Stage ('Run Unit Test') {
			step(
			sh 'cd /Projects/crowsoft_unittests'
			sh 'dotnet test'
			)
		}
    stage('Run Selenium Test') {
	  	steps {
		  	echo 'Selenium to go here'			
		  	}
		}	
	}
}

