pipeline {
  agent any
  stages {
    stage('Checkout code') {
	  	steps {
			echo 'This step checks out SCM code.'
		  	checkout scm				
				}
			}	
	stage ('Build MVC'){
		steps {
			echo '>>>>>> MSBuild <<<<<<<<<<<<<<'
			sh "cd /Projects/crowsoftmvc"
			sh "dotnet build"
			}
		}
		
	stage ('Build Unit Test') {
		steps {
			echo '>>>>>>  Unit Test <<<<<<<<<<<<<<'
			sh "cd /Projects/crowsoft_unittests"
			sh "dotnet test"
			}
		}
		
    stage ('Run Selenium Test') {
	  	steps {
		  	echo '>>>>>>Selenium Test<<<<<<<<<<<<<<'	
			}
		}	
		
	 stage('Stop app') {
	  	steps {	
			sshagent(['dev']) {
				echo '>>>>>> Stop App  <<<<<<<<<<<<<<'
				sh label: '', script: 'ansible devadmin@172.28.25.133 -a "sudo systemctl stop crowsoft-webapp.service" '
				}
			}
 		}
				
	 
	stage('Startapp') {
	  	steps {
			sshagent(['dev']) {
				echo '>>>>>> StartApp  <<<<<<<<<<<<<<'
				sh label: '', script: 'ansible devadmin@172.28.25.133 -a "sudo systemctl start crowsoft-webapp.service"'
				}
			}
		}
	}
}




